### ISSUE TITLE
Code review 28/1/2020

### ISSUE THREAD

**Issue by Fig77** [ricardovaltierra/ror_tutorial1#1]
* The heroku environment does not have the sqlite3 gem (and will never have it). It should use the postgreSQL gem 'pg' instead.
However, for some strange reason we could not find in the review, it is trying to use that (which should only be on development) on production.
A possible solution might be to use postgreSQL both on development and production, but we did not try that on our review.

* The project wasn't respecting git flow, merging needlessly to master, so a command that may be useful was presented. How to push branches using aliases:
```
git push -u heroku development:master
git get-url heroku
git remote get-url heroku
git remote set-url heroku <new-url>
```
* Other commands used during the code review.
```
heroku logs --tail
sqlite3 gem
heroku does not have that gem.
heroku uses postgreSQL
'pg' gem
git diff
git diff Gemfile
git push -u  heroku setup:master
gitk
git push --force -u heroku setup:master
Control + T
heroku run rails db:migrate
db/schema.rb
cat Gemfile | less
```

**Comment by ricardovaltierra** [comment]
The problem was solved with the following procedures:

- Bundler required upgrade to 2.x.x (link to tutorial: https://bundler.io/guides/bundler_2_upgrade.html)
- Prepeare system for deployment replacing 
```
gem 'pg', '0.20.0'
```
by just
```
gem 'pg'
```

avoiding version mismatching
